version = 0.1
[default.deploy.parameters]
stack_name = "daintymeal"
resolve_s3 = true
s3_prefix = "daintymeal"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
